import { Person } from "@/types/person";

export const mockPeople: Person[] = [
  {
    id: "1",
    name: "Alex Chen",
    bio: "Building AI-powered developer tools. Previously at Google. Always happy to chat about AI, startups, and building in public.",
    building: "Cursor AI",
    role: "founder",
    company: "Cursor",
    interests: ["AI", "Developer Tools", "SaaS"],
    twitter: "https://twitter.com/alexchen",
    linkedin: "https://linkedin.com/in/alexchen",
    website: "https://cursor.sh",
    avatar_url: null,
    location: "Shoreditch, London",
    communities: ["Cerebral Valley", "AI Builders"],
    open_to_connect: true,
    created_at: "2025-01-15T10:00:00Z",
    approval_status: "approved",
    approved_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    name: "Sarah Johnson",
    bio: "Full-stack developer passionate about building products that matter. Currently exploring AI agents and automation.",
    building: "AI Agent Platform",
    role: "developer",
    company: null,
    interests: ["AI", "Web Development", "Automation"],
    twitter: "https://twitter.com/sarahj",
    linkedin: "https://linkedin.com/in/sarahjohnson",
    website: null,
    avatar_url: null,
    location: "Camden, London",
    communities: ["AI Builders"],
    open_to_connect: true,
    created_at: "2025-01-16T10:00:00Z",
    approval_status: "approved",
    approved_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    name: "Michael Park",
    bio: "Early-stage investor focused on AI and developer tools. Always looking to meet exceptional founders building the future.",
    building: null,
    role: "investor",
    company: "Tech Ventures",
    interests: ["AI", "Developer Tools", "Early Stage"],
    twitter: "https://twitter.com/mpark",
    linkedin: "https://linkedin.com/in/michaelpark",
    website: "https://techventures.vc",
    avatar_url: null,
    location: "Mayfair, London",
    communities: ["Cerebral Valley"],
    open_to_connect: true,
    created_at: "2025-01-17T10:00:00Z",
    approval_status: "approved",
    approved_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    name: "Emma Williams",
    bio: "Product designer at a fintech startup. Love connecting with other designers and founders in the London tech scene.",
    building: "Fintech App",
    role: "designer",
    company: "FinTech Co",
    interests: ["Design", "Fintech", "Product"],
    twitter: "https://twitter.com/emmaw",
    linkedin: "https://linkedin.com/in/emmawilliams",
    website: null,
    avatar_url: null,
    location: "Islington, London",
    communities: [],
    open_to_connect: true,
    created_at: "2025-01-18T10:00:00Z",
    approval_status: "approved",
    approved_at: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
  },
];

