import { Event } from "@/types/event";

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Cafe Cursor London",
    description: "We're taking over a cafe for the day in London and inviting Cursor users to swing by. Bring your laptop with you and spend some time building with other Cursor users. We'll have some Cursor credits and coffee waiting for you. You can also just pop by for coffee and to say hi! A bunch of engineers from the Cursor team will be around throughout the day at the cafe.",
    date: "2025-02-08",
    start_time: "09:00",
    end_time: "17:00",
    venue: "Cafe (Location TBA)",
    location: "London, England",
    type: "meetup",
    topics: ["AI", "Cursor"],
    host_name: "Cursor Community",
    registration_url: "https://luma.com/cas88c02?tk=QiK4Kz",
    image_url: null,
    source: "luma",
    created_at: "2025-01-20T10:00:00Z",
  },
  {
    id: "2",
    title: "Build with Cursor: London",
    description: "We're bringing together a small group for an evening of building together at Granola's London office. We're piloting something new with the product and would love to get your take as you build! Bring your laptop, we'll set you up with comped Cursor credits for the event, and a bunch of engineers from the Cursor team will be around throughout the evening.",
    date: "2025-02-12",
    start_time: "18:00",
    end_time: "21:00",
    venue: "Granola's London Office",
    location: "London, England",
    type: "workshop",
    topics: ["AI", "Cursor", "Building"],
    host_name: "Cursor Community",
    registration_url: "https://luma.com/l8umo7yr?tk=22Od6a",
    image_url: null,
    source: "luma",
    created_at: "2025-01-21T10:00:00Z",
  },
  {
    id: "3",
    title: "Gemini 3 Hackathon London",
    description: "Gemini 3 has arrived; Google's most intelligent model yet, built for state-of-the-art reasoning, rich multimodal understanding, and bringing any idea to life with unprecedented depth and clarity. We're looking for the most ambitious concepts you can build with Gemini 3 across AI Studio, Vertex AI, and Google's new agentic development platform: Antigravity. Show the Google DeepMind team what you can create. Compete to win 150K Gemini API credits and an exclusive 30-minute virtual call with the founders of Google's AI Future Fund.",
    date: "2025-12-13",
    start_time: "09:00",
    end_time: "22:00",
    venue: "London, UK",
    location: "London, UK",
    type: "hackathon",
    topics: ["AI", "Gemini", "Google"],
    host_name: "Cerebral Valley & Google",
    registration_url: "https://cerebralvalley.ai/e/gemini-3-hackathon-london?tab=guest-list",
    image_url: null,
    source: "manual",
    created_at: "2025-01-22T10:00:00Z",
  },
];

