import { Event } from "@/types/event";

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "AI Builders London Meetup",
    description: "Join us for an evening of AI demos, networking, and discussions about the future of AI in London.",
    date: "2024-03-15",
    start_time: "18:00",
    end_time: "21:00",
    venue: "TechHub Shoreditch",
    location: "Shoreditch, London",
    type: "meetup",
    topics: ["AI", "Machine Learning"],
    host_name: "AI Builders London",
    registration_url: "https://lu.ma/ai-builders",
    image_url: null,
    source: "luma",
    created_at: "2024-03-01T10:00:00Z",
  },
  {
    id: "2",
    title: "Fintech Innovation Hackathon",
    description: "48-hour hackathon focused on building innovative fintech solutions. Prizes worth £10,000.",
    date: "2024-03-20",
    start_time: "09:00",
    end_time: "21:00",
    venue: "Level39",
    location: "Canary Wharf, London",
    type: "hackathon",
    topics: ["Fintech", "Blockchain"],
    host_name: "Fintech London",
    registration_url: "https://eventbrite.com/fintech-hackathon",
    image_url: null,
    source: "eventbrite",
    created_at: "2024-03-02T10:00:00Z",
  },
  {
    id: "3",
    title: "Web3 & Crypto Workshop",
    description: "Learn the fundamentals of Web3, smart contracts, and DeFi. Perfect for beginners and experienced developers.",
    date: "2024-03-18",
    start_time: "14:00",
    end_time: "17:00",
    venue: "Crypto Commons",
    location: "King's Cross, London",
    type: "workshop",
    topics: ["Crypto", "Web3", "Blockchain"],
    host_name: "London Web3 Community",
    registration_url: "https://lu.ma/web3-workshop",
    image_url: null,
    source: "luma",
    created_at: "2024-03-03T10:00:00Z",
  },
  {
    id: "4",
    title: "Startup Founders Networking",
    description: "Monthly networking event for startup founders, investors, and builders. Drinks and snacks provided.",
    date: "2024-03-22",
    start_time: "18:30",
    end_time: "21:00",
    venue: "The Hoxton",
    location: "Shoreditch, London",
    type: "networking",
    topics: ["Startups", "Venture Capital"],
    host_name: "London Startup Community",
    registration_url: "https://lu.ma/startup-networking",
    image_url: null,
    source: "luma",
    created_at: "2024-03-04T10:00:00Z",
  },
];

